# Generated by Django 3.0.7 on 2020-06-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativa',
            name='votos',
            field=models.IntegerField(default=0),
        ),
    ]
