# Generated by Django 3.0.7 on 2020-06-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_auto_20200612_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombres', models.CharField(max_length=35)),
                ('apellidos', models.CharField(max_length=35)),
                ('foto', models.ImageField(upload_to='')),
            ],
        ),
    ]
