# Generated by Django 3.0.7 on 2020-06-21 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_auto_20200620_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7),
        ),
    ]
